#!/usr/bin/env node

/**
 * Launch CLI - Initialize a vertical for a new client site
 *
 * Usage:
 *   npm run launch <vertical> [options]
 *   node scripts/launch.js hvac --name "ABC Heating"
 *
 * This script:
 * 1. Copies the vertical config to src/config/site.ts
 * 2. Creates the vertical-specific components
 * 3. Updates pages to use vertical components
 * 4. Validates prerequisites and shows what's needed
 */

const fs = require('fs');
const path = require('path');

// Available verticals
const VERTICALS = {
  hvac: {
    name: 'HVAC',
    config: 'src/verticals/home-services/config/hvac.ts',
    category: 'home-services',
  },
  plumbing: {
    name: 'Plumbing',
    config: 'src/verticals/home-services/config/plumbing.ts',
    category: 'home-services',
  },
};

// Parse command line arguments
const args = process.argv.slice(2);
const vertical = args[0]?.toLowerCase();
const options = parseOptions(args.slice(1));

// Show help if no vertical specified
if (!vertical || vertical === '--help' || vertical === '-h') {
  showHelp();
  process.exit(0);
}

// Validate vertical
if (!VERTICALS[vertical]) {
  console.error(`\n❌ Unknown vertical: "${vertical}"\n`);
  console.error('Available verticals:');
  Object.entries(VERTICALS).forEach(([key, val]) => {
    console.error(`  - ${key} (${val.name})`);
  });
  process.exit(1);
}

// Run launch
launch(vertical, options);

// ============================================================================
// Main launch function
// ============================================================================

async function launch(vertical, options) {
  const config = VERTICALS[vertical];

  console.log(`
╔══════════════════════════════════════════════════════════════╗
║                    NOCMS SITE LAUNCHER                       ║
╠══════════════════════════════════════════════════════════════╣
║  Vertical: ${config.name.padEnd(48)}║
║  Category: ${config.category.padEnd(48)}║
╚══════════════════════════════════════════════════════════════╝
`);

  // Step 1: Check if already initialized
  const siteConfigPath = path.join(process.cwd(), 'src/config/vertical.ts');
  if (fs.existsSync(siteConfigPath) && !options.force) {
    console.log('⚠️  Site already initialized with a vertical.');
    console.log('   Use --force to reinitialize.\n');
    process.exit(1);
  }

  // Step 2: Copy vertical config
  console.log('📋 Step 1: Setting up vertical configuration...');
  copyVerticalConfig(vertical, config);

  // Step 3: Create vertical marker file
  console.log('📍 Step 2: Creating vertical marker...');
  createVerticalMarker(vertical, config);

  // Step 4: Show prerequisites
  console.log('📝 Step 3: Checking prerequisites...\n');
  showPrerequisites(vertical);

  // Step 5: Show next steps
  showNextSteps(vertical, config, options);
}

// ============================================================================
// Helper functions
// ============================================================================

function copyVerticalConfig(vertical, config) {
  const sourcePath = path.join(process.cwd(), config.config);
  const destDir = path.join(process.cwd(), 'src/config');
  const destPath = path.join(destDir, 'vertical.ts');

  // Ensure config directory exists
  if (!fs.existsSync(destDir)) {
    fs.mkdirSync(destDir, { recursive: true });
  }

  // Read source config
  if (!fs.existsSync(sourcePath)) {
    console.error(`❌ Vertical config not found: ${sourcePath}`);
    process.exit(1);
  }

  const sourceContent = fs.readFileSync(sourcePath, 'utf-8');

  // Add re-export wrapper
  const content = `/**
 * Active Vertical Configuration
 *
 * This file was generated by: npm run launch ${vertical}
 * Generated at: ${new Date().toISOString()}
 *
 * To customize, edit the values below.
 * To switch verticals, run: npm run launch <vertical> --force
 */

${sourceContent}

// Re-export as active config
export { ${vertical}Config as verticalConfig };
`;

  fs.writeFileSync(destPath, content);
  console.log(`   ✓ Created src/config/vertical.ts\n`);
}

function createVerticalMarker(vertical, config) {
  const markerPath = path.join(process.cwd(), '.vertical');
  const content = JSON.stringify({
    vertical,
    name: config.name,
    category: config.category,
    initializedAt: new Date().toISOString(),
  }, null, 2);

  fs.writeFileSync(markerPath, content);
  console.log(`   ✓ Created .vertical marker file\n`);
}

function showPrerequisites(vertical) {
  // These are the common prerequisites - in a real implementation,
  // we'd parse the config file to extract these dynamically
  const prerequisites = {
    hvac: [
      { feature: 'Financing', requirement: 'Active financing partner account (Synchrony, GreenSky, etc.)', priority: 'high' },
      { feature: 'Gallery', requirement: 'Minimum 3 project photos with before/after shots', priority: 'medium' },
      { feature: 'Reviews', requirement: 'Google Business Profile with minimum 5 reviews', priority: 'high' },
      { feature: 'Trust Badge: BBB', requirement: 'BBB accreditation (optional)', priority: 'low' },
      { feature: 'Trust Badge: Google Rating', requirement: 'Google Business Profile', priority: 'high' },
    ],
    plumbing: [
      { feature: 'Financing', requirement: 'Active financing partner account', priority: 'high' },
      { feature: 'Gallery', requirement: 'Minimum 3 project photos', priority: 'medium' },
      { feature: 'Reviews', requirement: 'Google Business Profile with minimum 5 reviews', priority: 'high' },
    ],
  };

  const prereqs = prerequisites[vertical] || [];

  if (prereqs.length === 0) {
    console.log('   ✓ No prerequisites required!\n');
    return;
  }

  console.log('   Prerequisites for enabled features:\n');

  const byPriority = {
    high: prereqs.filter(p => p.priority === 'high'),
    medium: prereqs.filter(p => p.priority === 'medium'),
    low: prereqs.filter(p => p.priority === 'low'),
  };

  if (byPriority.high.length > 0) {
    console.log('   🔴 HIGH PRIORITY (needed for launch):');
    byPriority.high.forEach(p => {
      console.log(`      • ${p.feature}: ${p.requirement}`);
    });
    console.log('');
  }

  if (byPriority.medium.length > 0) {
    console.log('   🟡 MEDIUM PRIORITY (needed soon):');
    byPriority.medium.forEach(p => {
      console.log(`      • ${p.feature}: ${p.requirement}`);
    });
    console.log('');
  }

  if (byPriority.low.length > 0) {
    console.log('   🟢 LOW PRIORITY (nice to have):');
    byPriority.low.forEach(p => {
      console.log(`      • ${p.feature}: ${p.requirement}`);
    });
    console.log('');
  }
}

function showNextSteps(vertical, config, options) {
  console.log(`
╔══════════════════════════════════════════════════════════════╗
║                        NEXT STEPS                            ║
╚══════════════════════════════════════════════════════════════╝

1. Update business information:
   Edit src/config/vertical.ts → business section

2. Customize features (enable/disable):
   Edit src/config/vertical.ts → features section

3. Add your content:
   - Logo: public/images/logo.png
   - Photos: public/images/gallery/
   - Blog posts: src/content/blog/

4. Start development server:
   npm run dev

5. When ready to deploy:
   npm run build

For full documentation, see:
   docs/SETUP.md
   docs/VERTICALS.md
   docs/GAMEPLAN-HVAC-PLUMBING.md

`);
}

function parseOptions(args) {
  const options = {
    force: false,
    name: null,
  };

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg === '--force' || arg === '-f') {
      options.force = true;
    } else if (arg === '--name' || arg === '-n') {
      options.name = args[++i];
    }
  }

  return options;
}

function showHelp() {
  console.log(`
NOCMS Site Launcher
━━━━━━━━━━━━━━━━━━━

Initialize a new site with a specific vertical configuration.

USAGE:
  npm run launch <vertical> [options]

VERTICALS:
  hvac        HVAC contractor website
  plumbing    Plumbing contractor website

OPTIONS:
  --force, -f    Reinitialize even if already set up
  --name, -n     Business name (optional, can set in config)
  --help, -h     Show this help message

EXAMPLES:
  npm run launch hvac
  npm run launch plumbing --force
  npm run launch hvac --name "ABC Heating & Cooling"

WORKFLOW:
  1. Clone the nocms repository
  2. Run: npm install
  3. Run: npm run launch <vertical>
  4. Edit src/config/vertical.ts with your details
  5. Run: npm run dev
  6. Customize pages and content
  7. Deploy!
`);
}
